name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  edit-read-me_test:
    runs-on: macos-latest
    steps:
      - run: echo "hello world" 
      - run: pwd

